### ISSUE TITLE
Continue animation on click?

### ISSUE THREAD

**Issue by behiunforgiven** [Mindinventory/animated_icons#1]
How to implement continue animation on click?

**Comment by aespatelmi** [comment]
You need to pass IconType.continueAnimation in iconType parameter.

                    AnimateIcon(
                          key: UniqueKey(),
                          onTap: () {},
                          iconType: IconType.continueAnimation,
                          height: 70,
                          width: 70,
                          color: Color.fromRGBO(
                              Random.secure().nextInt(255),
                              Random.secure().nextInt(255),
                              Random.secure().nextInt(255),
                              1),
                          animateIcon: AnimateIcons.bell ,
                        ),

**Comment by behiunforgiven** [comment]
I think this code implements playing animation from the beginning. I want a stopped animation, but when I tap, it starts playing.

**Comment by mi-ghanshyam** [comment]
You have to change the property `iconType` from `onlyIcon` to `continueAnimation`  at run time.
Don't forget to remove `UniqueKey ` in constrture.
