### ISSUE TITLE
All Tickers must be disposed before calling super.dispose()

### ISSUE THREAD

**Issue by slhezn** [Mindinventory/animated_icons#2]
Hi, 

Thanks for cool library...

My Codes...
`class _SaveButtonIcon extends StatelessWidget {
  const _SaveButtonIcon({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) => AnimateIcon(
      onTap: () => context.read<LoginRegisterLogic>().save(context),
      iconType: context.watch<LoginRegisterLogic>().iconType,
      animateIcon: context.watch<LoginRegisterLogic>().icon,
      color: Theme.of(context).cardColor);
}`

and this is error:

════════ Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown while finalizing the widget tree:
_AnimateIconState#7a4a2(tickers: tracking 1 ticker) was disposed with an active Ticker.

_AnimateIconState created a Ticker via its TickerProviderStateMixin, but at the time dispose() was called on the mixin, that Ticker was still active. All Tickers must be disposed before calling super.dispose().

Tickers used by AnimationControllers should be disposed by calling dispose() on the AnimationController itself. Otherwise, the ticker will leak.

**Comment by deep-mindinventory** [comment]
@slhezn please check out a new version. It is fixed. Thanks.
