### ISSUE TITLE
Version solving issue

### ISSUE THREAD

**Issue by SpirikleOfficial** [Mindinventory/animated_icons#4]
Hi , i'm having the following error:

Because animated_icon 0.0.4 depends on lottie ^1.4.0 and no versions of animated_icon match >0.0.4 <0.1.0, animated_icon ^0.0.4 requires lottie ^1.4.0.
So, because scanos depends on both animated_icon ^0.0.4 and lottie ^2.1.0, version solving failed.
pub get failed (1; So, because scanos depends on both animated_icon ^0.0.4 and lottie ^2.1.0, version solving failed.)

Please look into this. Thank You so much.

**Comment by mohit-chauhan-mi** [comment]
@SpirikleOfficial Fixed this, please check it with the latest [version](https://pub.dev/packages/animated_icon/versions/0.0.5). Thanks.
