### ISSUE TITLE
Follow dart conventions

### ISSUE THREAD

**Issue by sebastianbuechler** [Mindinventory/animated_icons#8]
Follow Dart file conventions
 for easier bug filing:

0/10 points: Provide a valid pubspec.yaml
Repository URL doesn't exist.
At the time of the analysis https://github.com/Mindinventory/animated_icons was unreachable. Make sure that the website is reachable via [HEAD](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/HEAD) requests.

Issue tracker URL doesn't exist.
At the time of the analysis https://github.com/Mindinventory/animated_icons/issues was unreachable. Make sure that the website is reachable via [HEAD](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/HEAD) requests.

**Comment by jaydeepkaria-mi** [comment]
Please check it with the [latest version](https://pub.dev/packages/animated_icon) . Thanks

**Comment by jaydeepkaria-mi** [comment]
Closing this issue for now.
